### ISSUE TITLE
The command returned with 'ok' value of 0"

### ISSUE THREAD

**Issue by veamia** [paulmelnikow/ObjCMongoDB#27]
The command returned with 'ok' value of 0"

**Comment by Ethavn** [comment]
The same problem. when i use the "authenticate" method, and return the error when go to the step "mongo_run_command".

**Comment by keefo** [comment]
Same issue here.
```
auth failed Error Domain=MongoDB Code=10 "MONGO_COMMAND_FAILED: The command returned with 'ok' value of 0" UserInfo={NSLocalizedDescription=MONGO_COMMAND_FAILED: The command returned with 'ok' value of 0}
```

**Comment by ddll184** [comment]
please check you mongoldb version.
if version is higher than 3.0 , you must modify auth schema mode.
(system.version.authSchema, current value is 5, please modify to 3)

the reason is default auth schema mode have been changed from 3.0

**Comment by paulmelnikow** [comment]
For more detail about why that's necessary, see #22.
